/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Fixture = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'court' : IDL.Text,
  'awayPlayer' : IDL.Text,
  'homePlayer' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const LeagueEntry = IDL.Record({
  'id' : IDL.Nat,
  'rank' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'playerName' : IDL.Text,
  'draws' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'defenseRating' : IDL.Nat,
  'name' : IDL.Text,
  'serveRating' : IDL.Nat,
  'nationality' : IDL.Text,
  'overallRating' : IDL.Nat,
  'attackRating' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Nat,
  'matchTag' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFixture' : IDL.Func([Fixture], [], []),
  'createLeagueEntry' : IDL.Func([LeagueEntry], [], []),
  'createPlayer' : IDL.Func([Player], [], []),
  'deleteFixture' : IDL.Func([IDL.Nat], [], []),
  'deleteLeagueEntry' : IDL.Func([IDL.Nat], [], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [], []),
  'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllFixtures' : IDL.Func([], [IDL.Vec(Fixture)], ['query']),
  'getAllLeagueEntries' : IDL.Func([], [IDL.Vec(LeagueEntry)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFixture' : IDL.Func([IDL.Nat], [Fixture], ['query']),
  'getLeagueEntry' : IDL.Func([IDL.Nat], [LeagueEntry], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [Player], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postChatMessage' : IDL.Func([ChatMessage], [], []),
  'updateFixture' : IDL.Func([Fixture], [], []),
  'updateLeagueEntry' : IDL.Func([LeagueEntry], [], []),
  'updatePlayer' : IDL.Func([Player], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Fixture = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'court' : IDL.Text,
    'awayPlayer' : IDL.Text,
    'homePlayer' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const LeagueEntry = IDL.Record({
    'id' : IDL.Nat,
    'rank' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'playerName' : IDL.Text,
    'draws' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'defenseRating' : IDL.Nat,
    'name' : IDL.Text,
    'serveRating' : IDL.Nat,
    'nationality' : IDL.Text,
    'overallRating' : IDL.Nat,
    'attackRating' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Nat,
    'matchTag' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFixture' : IDL.Func([Fixture], [], []),
    'createLeagueEntry' : IDL.Func([LeagueEntry], [], []),
    'createPlayer' : IDL.Func([Player], [], []),
    'deleteFixture' : IDL.Func([IDL.Nat], [], []),
    'deleteLeagueEntry' : IDL.Func([IDL.Nat], [], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [], []),
    'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllFixtures' : IDL.Func([], [IDL.Vec(Fixture)], ['query']),
    'getAllLeagueEntries' : IDL.Func([], [IDL.Vec(LeagueEntry)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFixture' : IDL.Func([IDL.Nat], [Fixture], ['query']),
    'getLeagueEntry' : IDL.Func([IDL.Nat], [LeagueEntry], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [Player], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postChatMessage' : IDL.Func([ChatMessage], [], []),
    'updateFixture' : IDL.Func([Fixture], [], []),
    'updateLeagueEntry' : IDL.Func([LeagueEntry], [], []),
    'updatePlayer' : IDL.Func([Player], [], []),
  });
};

export const init = ({ IDL }) => { return []; };