/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
  'matchTag' : [] | [string],
}
export interface Fixture {
  'id' : bigint,
  'status' : string,
  'court' : string,
  'awayPlayer' : string,
  'homePlayer' : string,
  'dateTime' : string,
}
export interface LeagueEntry {
  'id' : bigint,
  'rank' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'playerName' : string,
  'draws' : bigint,
  'points' : bigint,
}
export interface Player {
  'id' : bigint,
  'defenseRating' : bigint,
  'name' : string,
  'serveRating' : bigint,
  'nationality' : string,
  'overallRating' : bigint,
  'attackRating' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFixture' : ActorMethod<[Fixture], undefined>,
  'createLeagueEntry' : ActorMethod<[LeagueEntry], undefined>,
  'createPlayer' : ActorMethod<[Player], undefined>,
  'deleteFixture' : ActorMethod<[bigint], undefined>,
  'deleteLeagueEntry' : ActorMethod<[bigint], undefined>,
  'deletePlayer' : ActorMethod<[bigint], undefined>,
  'getAllChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllFixtures' : ActorMethod<[], Array<Fixture>>,
  'getAllLeagueEntries' : ActorMethod<[], Array<LeagueEntry>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFixture' : ActorMethod<[bigint], Fixture>,
  'getLeagueEntry' : ActorMethod<[bigint], LeagueEntry>,
  'getPlayer' : ActorMethod<[bigint], Player>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postChatMessage' : ActorMethod<[ChatMessage], undefined>,
  'updateFixture' : ActorMethod<[Fixture], undefined>,
  'updateLeagueEntry' : ActorMethod<[LeagueEntry], undefined>,
  'updatePlayer' : ActorMethod<[Player], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];